# ------ root_path/dataset_name ------
root_path: '/home/jianglongyu/mydrive/clip_dataset/train_dataset'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'custom_dataset'
shots: 16
backbone: 'ViT-B/32'

lr: 0.001
augment_epoch: 10
train_epoch: 20

# ------ Evaluate ------
THRESHOLDS: [
            [26.5, 27.1, 27.2, 27.3, 27.4],
            [23.3, 23.4, 23.6, 23.7, 23.8],
            [27.8, 27.9, 28.1, 28.2, 28.3],
            [26.8, 26.9, 27.1, 27.2, 27.3],
            [28.3, 28.4, 28.6, 28.7, 28.8]
        ]