# ------ root_path/dataset_name ------
# root_path: '/home/jianglongyu/Documents/datasets/clip_dataset_test'
root_path: '/home/jianglongyu/Documents/datasets/clip_dataset'
OUTPUT_DIR: '/home/jianglongyu/Documents/mllm/tip_adapter/output'


# ------ Load Cache and Features ------
# load_cache: False
# load_pre_feat: False

load_cache: True
load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'custom_dataset'
shots: 16
backbone: 'ViT-B/32'

lr: 0.001
augment_epoch: 10
train_epoch: 20

# ------ Evaluate ------
# origin model
thresholds: [
    [25.7, 25.8, 25.9, 26.5, 26.6], # doughnut
    [23.8, 24, 24.1, 24.15, 24.2], # glass cup
    [27.8, 27.9, 27.95, 28.01, 28.05], # lemon
    [25.4, 25.5, 25.55, 25.9, 26.3], # chinese noodle
    [29.5, 29.8, 30.1, 30.2, 30.3] # chinese flute
]

# tip-adapter
tip_thresholds: [
    [40.65, 40.68, 40.75, 40.8, 40.85], # doughnut
    [40.3, 40.4, 40.5, 40.6, 40.7], # glass cup
    [44.3, 44.4, 44.5, 44.6, 44.7], # lemon
    [40.85, 40.9, 41, 41.1, 41.15,], # chinese noodle
    [42.3, 42.4, 42.5, 42.6, 42.7] # chinese flute
]