# ------ root_path/dataset_name ------
# root_path: '/home/jianglongyu/Documents/datasets/clip_dataset_test'
root_path: '/home/jianglongyu/Documents/datasets/clip_dataset'
OUTPUT_DIR: '/home/jianglongyu/Documents/mllm/tip_adapter/output'


# ------ Load Cache and Features ------
# load_cache: False
# load_pre_feat: False

load_cache: True
load_pre_feat: True


# ------ Hyperparamters ------
# search_hp: True
search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'custom_dataset'
shots: 500
backbone: 'ViT-B/32'

lr: 0.001
augment_epoch: 10
train_epoch: 10

# ------ Evaluate ------
# origin model
thresholds: [
    [25.7, 25.8, 25.9, 26.5, 26.6], # doughnut
    [23.8, 24, 24.1, 24.15, 24.2], # glass cup
    [27.8, 27.9, 27.95, 28.01, 28.05], # lemon
    [25.4, 25.5, 25.55, 25.9, 26.3], # chinese noodle
    [29.5, 29.8, 30.1, 30.2, 30.3] # chinese flute
]

# tip-adapter
# shot: 8
# tip_thresholds: [
#     [33.2, 33.3, 33.4, 33.5, 33.6], # doughnut
#     [33.2, 33.3, 33.4, 33.5, 33.6], # glass cup
#     [36.8, 36.9, 37, 37.05, 37.1], # lemon
#     [32.8, 33, 33.5, 34, 34.5], # chinese noodle
#     [36.45, 36.5, 36.55, 36.6, 36.65] # chinese flute
# ]

# # shot: 16
# tip_thresholds: [
#     [40.65, 40.68, 40.75, 40.8, 40.85], # doughnut
#     [40.3, 40.4, 40.5, 40.6, 40.7], # glass cup
#     [44.3, 44.4, 44.5, 44.6, 44.7], # lemon
#     [40.85, 40.9, 41, 41.1, 41.15], # chinese noodle
#     [42.3, 42.4, 42.5, 42.6, 42.7] # chinese flute
# ]

# # shot: 32
# tip_thresholds: [
#     [55.6, 55.65, 55.7, 55.71, 55.72], # doughnut
#     [53.4, 53.5, 53.6, 53.65, 53.7], # glass cup
#     [59, 59.05, 59.1, 59.2, 59.3], # lemon
#     [55.1, 55.2, 55.3, 55.4, 55.5], # chinese noodle
#     [55.5, 55.55, 55.58, 55.59, 55.6] # chinese flute
# ]

# # shot: 100
# tip_thresholds: [
#     [116, 117, 118, 118.5, 119], # doughnut
#     [119, 119.5, 110, 110.5, 111], # glass cup
#     [124, 125, 125.5, 126, 126.5], # lemon
#     [116, 117, 118, 118.5, 119], # chinese noodle
#     [114, 114, 115, 116, 117] # chinese flute
# ]

# shot: 500
tip_thresholds: [
    [459, 460, 461, 462, 463], # doughnut
    [454, 455, 456, 457, 458], # glass cup
    [498, 499, 500, 501, 502], # lemon
    [493, 494, 495, 496, 497], # chinese noodle
    [458, 459, 460, 461, 462] # chinese flute
]

# tip_thresholds: [
#     [40.85, 41, 42, 43, 44], # doughnut
#     [39, 40, 40.3, 40.7, 41], # glass cup
#     [41, 42, 43, 44, 44.3], # lemon
#     [40.85, 40.9, 41, 41.1, 41.15,], # chinese noodle
#     [42.7, 43, 44, 45, 46] # chinese flute
# ]